{% set version = '1.23.120.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bipartitemodularitymaximization
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BipartiteModularityMaximization_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BipartiteModularityMaximization/BipartiteModularityMaximization_{{ version }}.tar.gz
  sha256: 2b9833e12d54c7ac244cd09a815767844bc2dd0daa687fdaebcf6e359e67e95f

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'                        # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp

test:
  requires:
    - r-testthat
  commands:
    - $R -e "library('BipartiteModularityMaximization')"                 # [not win]
    - $R -e "testthat::test_package('BipartiteModularityMaximization')"  # [not win]
    - "\"%R%\" -e \"library('BipartiteModularityMaximization')\""                 # [win]
    - "\"%R%\" -e \"testthat::test_package('BipartiteModularityMaximization')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=BipartiteModularityMaximization
  license: MIT
  summary: "Function bipmod() that partitions a bipartite network into non-overlapping biclusters
    by maximizing bipartite modularity defined in Barber (2007) <doi:10.1103/PhysRevE.76.066102>
    using the bipartite version of the algorithm described in Trevi\xF1o (2015) <doi:10.1088/1742-5468/2015/02/P02003>."
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ezherman

# Package: BipartiteModularityMaximization
# Title: Partition Bipartite Network into Non-Overlapping Biclusters by Optimizing Bipartite Modularity
# Version: 1.23.120.1
# Authors@R: c(person(given = "Tianlong",family = "Chen",role = c("aut"),),person(given = "Weibin",family = "Zhang",role = c( "cre","ctb"),email = "wbzhang.ustc@gmail.com"),person(given = "Suresh",family = "Bhavnani",role = c("cph","fnd"),email = "subhavna@UTMB.EDU"))
# Author: Tianlong Chen [aut], Weibin Zhang [cre, ctb], Suresh Bhavnani [cph, fnd]
# Maintainer: Weibin Zhang <wbzhang.ustc@gmail.com>
# Description: Function bipmod() that partitions a bipartite network into non-overlapping biclusters by maximizing bipartite modularity defined in Barber (2007) <doi:10.1103/PhysRevE.76.066102> using the bipartite version of the algorithm described in Trevino (2015) <doi:10.1088/1742-5468/2015/02/P02003>.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# LinkingTo: Rcpp
# Imports: Rcpp
# RoxygenNote: 7.1.2
# Depends: R (>= 2.10)
# Suggests: testthat
# NeedsCompilation: yes
# Packaged: 2023-01-21 00:16:03 UTC; weibzhan
# Repository: CRAN
# Date/Publication: 2023-01-21 23:20:30 UTC
